### ISSUE TITLE
Request: derivatives and integrals

### ISSUE THREAD

**Issue by roger-** [c-f-h/baryrat#2]
Some other packages [have derivatives](https://juliahub.com/ui/Packages/BaryRational/zXG6Y/0.1.0) and I'm not sure if integrals have a efficient representation.

**Comment by c-f-h** [comment]
I've implemented evaluation of first and second derivatives: https://baryrat.readthedocs.io/en/latest/#baryrat.BarycentricRational.eval_deriv

I've also pushed a new version to PyPI so you can upgrade with pip.

I'm not aware of integral representations but if you find anything, let me know.
